### ISSUE TITLE
UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)

### ISSUE THREAD

**Issue by leeman99** [welaika/wordmove#111]
First off thanks for creating such an amazing tool! Wordmove is really going to change our workflow! I've managed to get everything up and running, and am able to send my theme, plugins, core, etc. to our LAMP box on Digital Ocean. The only thing I'm encountering is this issue with the database sync.

```
/Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:55:in `remote_run': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:62:in `download_remote_db'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:18:in `push_db'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:58:in `block in push'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:34:in `block in handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:57:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'
```

I've adjusted the sql_adapter.sb file to include the UTF 8 line suggested in previous fixes, and I've registered my pass with my server, as also suggested. Yamllint also verifies the movefile.

Thanks in advance for any help!

**Comment by delphaber** [comment]
Hi, we decided to *not* fix this because probably there's a problem with your database and you should try to fix it without losing data. Please, read this wiki page https://github.com/welaika/wordmove/wiki/invalid-byte-sequence-in-UTF-8-while-pushing---pulling-db for more information
