### ISSUE TITLE
Database push fails (Error 404)

### ISSUE THREAD

**Issue by mariojankovic** [welaika/wordmove#128]
I've managed to upload everything except my database. Looking through all the other issues didn't help.

    remote | write /public_html/beta/wp-content/dump.php
        local | download http://masked.com/wp-content/dump.php?shared_key=MASKED > /vagrant/wordpress/masked/wp-content/remote-backup-1425131007.sql
        /usr/lib/ruby/1.9.1/open-uri.rb:346:in `open_http': 404 Not Found (OpenURI::HTTPError)
            from /usr/lib/ruby/1.9.1/open-uri.rb:775:in `buffer_open'
            from /usr/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
            from /usr/lib/ruby/1.9.1/open-uri.rb:201:in `catch'
            from /usr/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
            from /usr/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
            from /usr/lib/ruby/1.9.1/open-uri.rb:677:in `open'
            from /usr/lib/ruby/1.9.1/open-uri.rb:33:in `open'
            from /var/lib/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:155:in `block in download'
            from /usr/lib/ruby/1.9.1/open-uri.rb:35:in `open'
            from /usr/lib/ruby/1.9.1/open-uri.rb:35:in `open'
            from /var/lib/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:154:in `download'
            from /var/lib/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/deployer/ftp.rb:106:in `download_remote_db'
            from /var/lib/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/deployer/ftp.rb:23:in `push_db'
            from /var/lib/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:58:in `block in push'
            from /var/lib/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:34:in `block in handle_options'
            from /var/lib/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `each'
            from /var/lib/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `handle_options'
            from /var/lib/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:57:in `push'
            from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
            from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
            from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
            from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
            from /var/lib/gems/1.9.1/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
            from /usr/local/bin/wordmove:23:in `load'
            from /usr/local/bin/wordmove:23:in `<main>'
        vagrant@vagrant-ubuntu-trusty-64:/vagrant/wordpress/$

By the way, I'm using Vagrantpress on a Windows machine.

**Comment by pioneerskies** [comment]
Sorry for the long waited reply... :(

This is an unknown development environment for me...so my troubleshoot would begin rally far away...

* http://masked.com is usually achievable?
* why are you using FTP method to access a vagrant machine? Isn't SSH more straightforward?

**Comment by pioneerskies** [comment]
Closing for inactivity. Feel free to reopen
