### ISSUE TITLE
rsync error: error in rsync protocol data stream (code 12)

### ISSUE THREAD

**Issue by nailbrain** [welaika/wordmove#162]

**Comment by pioneerskies** [comment]
Before to look at your `Movefile` I'd like to give you a little advice: if you are working w/ MediaTemple it'll never happens that you'll have a path like `/domains/websouthend.co.uk/html/`, but you'll more realistically have smtng like `/nfs/cxx/hxx/mnt/xxxxxxx/users/.home/domains/websouthend.co.uk/html/`

Plz, check your absolute path using the following command adapted to your credentials

```
$ ssh user@host pwd`
```

that will be the absolute path to your user's home directory. You'll build the absolute path of a host starting from that path.

Unfortunately the lunk http://www.codeshare.io/BiOqf is dead. I swear I've never seen errors like

```
Ignoring eventmachine-1.0.3 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.3
Ignoring mysql2-0.3.15 because its extensions are not built.  Try: gem pristine mysql2 --version 0.3.15
Ignoring sqlite3-1.3.9 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.9
Ignoring sqlite3-1.3.8 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.8
Ignoring thin-1.6.0 because its extensions are not built.  Try: gem pristine thin --version 1.6.0
```

In that moment I have no idea what is happening... http://www.funelf.net/photos/I-have-no-idea-what-i%60m-doing.jpg O_O

**Comment by nailbrain** [comment]
Thanks pioneerskies but I updated my path and am still getting thrown a bunch of errors.

`▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
Ignoring eventmachine-1.0.3 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.3
Ignoring mysql2-0.3.15 because its extensions are not built.  Try: gem pristine mysql2 --version 0.3.15
Ignoring sqlite3-1.3.9 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.9
Ignoring sqlite3-1.3.8 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.8
Ignoring thin-1.6.0 because its extensions are not built.  Try: gem pristine thin --version 1.6.0

▬▬ ✓ Pushing wordpress core ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | put_directory: /Dropbox/htdocs/thelanguagepeople /nfs/c06/h08/mnt/155271/domains/thelanguagepeople .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql wp-content/*
I, [2015-05-29T22:11:29.316579 #3709]  INFO -- : rsync --progress -e 'sshpass -p Juicechase88! ssh -p 22 websouthend.co.uk@s155271.gridserver.com' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude bin/ --exclude 'tmp/*' --exclude 'Gemfile*' --exclude Movefile --exclude wp-config.php --exclude 'wp-content/*.sql' --exclude 'wp-content/*' /Dropbox/htdocs/thelanguagepeople/ :/nfs/c06/h08/mnt/155271/domains/thelanguagepeople
building file list ... 
rsync: link_stat "/Dropbox/htdocs/thelanguagepeople/." failed: No such file or directory (2)
0 files to consider

sent 178 bytes  received 20 bytes  30.46 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]

▬▬ ✓ Pushing Uploads ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | put_directory: /Dropbox/htdocs/thelanguagepeople/wp-content/uploads /nfs/c06/h08/mnt/155271/domains/thelanguagepeople/wp-content/uploads .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql wp-content/*
I, [2015-05-29T22:11:36.021468 #3709]  INFO -- : rsync --progress -e 'sshpass -p Juicechase88! ssh -p 22 websouthend.co.uk@s155271.gridserver.com' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude bin/ --exclude 'tmp/*' --exclude 'Gemfile*' --exclude Movefile --exclude wp-config.php --exclude 'wp-content/*.sql' --exclude 'wp-content/*' /Dropbox/htdocs/thelanguagepeople/wp-content/uploads/ :/nfs/c06/h08/mnt/155271/domains/thelanguagepeople/wp-content/uploads
building file list ... 
rsync: link_stat "/Dropbox/htdocs/thelanguagepeople/wp-content/uploads/." failed: No such file or directory (2)
0 files to consider

sent 178 bytes  received 20 bytes  26.40 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]

▬▬ ✓ Pushing Themes ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | put_directory: /Dropbox/htdocs/thelanguagepeople/wp-content/themes /nfs/c06/h08/mnt/155271/domains/thelanguagepeople/wp-content/themes .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql wp-content/*
I, [2015-05-29T22:11:43.691887 #3709]  INFO -- : rsync --progress -e 'sshpass -p Juicechase88! ssh -p 22 websouthend.co.uk@s155271.gridserver.com' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude bin/ --exclude 'tmp/*' --exclude 'Gemfile*' --exclude Movefile --exclude wp-config.php --exclude 'wp-content/*.sql' --exclude 'wp-content/*' /Dropbox/htdocs/thelanguagepeople/wp-content/themes/ :/nfs/c06/h08/mnt/155271/domains/thelanguagepeople/wp-content/themes
building file list ... 
rsync: link_stat "/Dropbox/htdocs/thelanguagepeople/wp-content/themes/." failed: No such file or directory (2)
0 files to consider

sent 178 bytes  received 20 bytes  30.46 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]

▬▬ ✓ Pushing Plugins ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | put_directory: /Dropbox/htdocs/thelanguagepeople/wp-content/plugins /nfs/c06/h08/mnt/155271/domains/thelanguagepeople/wp-content/plugins .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql wp-content/*
I, [2015-05-29T22:11:49.938286 #3709]  INFO -- : rsync --progress -e 'sshpass -p Juicechase88! ssh -p 22 websouthend.co.uk@s155271.gridserver.com' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude bin/ --exclude 'tmp/*' --exclude 'Gemfile*' --exclude Movefile --exclude wp-config.php --exclude 'wp-content/*.sql' --exclude 'wp-content/*' /Dropbox/htdocs/thelanguagepeople/wp-content/plugins/ :/nfs/c06/h08/mnt/155271/domains/thelanguagepeople/wp-content/plugins
building file list ... 
rsync: link_stat "/Dropbox/htdocs/thelanguagepeople/wp-content/plugins/." failed: No such file or directory (2)
0 files to consider

sent 178 bytes  received 20 bytes  18.86 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]

▬▬ ✓ Pushing Languages ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | put_directory: /Dropbox/htdocs/thelanguagepeople/wp-content/languages /nfs/c06/h08/mnt/155271/domains/thelanguagepeople/wp-content/languages .git/ .gitignore .sass-cache/ bin/ tmp/* Gemfile* Movefile wp-config.php wp-content/*.sql wp-content/*
I, [2015-05-29T22:11:59.562731 #3709]  INFO -- : rsync --progress -e 'sshpass -p Juicechase88! ssh -p 22 websouthend.co.uk@s155271.gridserver.com' -rlpt --compress --omit-dir-times --delete --exclude .git/ --exclude .gitignore --exclude .sass-cache/ --exclude bin/ --exclude 'tmp/*' --exclude 'Gemfile*' --exclude Movefile --exclude wp-config.php --exclude 'wp-content/*.sql' --exclude 'wp-content/*' /Dropbox/htdocs/thelanguagepeople/wp-content/languages/ :/nfs/c06/h08/mnt/155271/domains/thelanguagepeople/wp-content/languages
building file list ... 
rsync: link_stat "/Dropbox/htdocs/thelanguagepeople/wp-content/languages/." failed: No such file or directory (2)
0 files to consider

sent 178 bytes  received 20 bytes  26.40 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]

▬▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | mysqldump --host=external-db.s155271.gridserver.com --user=db155271_brett --password=cQm-7EA-nB8-FuU db155271_lang > /nfs/c06/h08/mnt/155271/domains/thelanguagepeople/wp-content/dump.sql
   remote | get: /nfs/c06/h08/mnt/155271/domains/thelanguagepeople/wp-content/dump.sql /Dropbox/htdocs/thelanguagepeople/wp-content/staging-backup-1432912327.sql
/Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-scp-1.2.1/lib/net/scp/download.rb:156:in `initialize': No such file or directory @ rb_sysopen - /Dropbox/htdocs/thelanguagepeople/wp-content/staging-backup-1432912327.sql (Errno::ENOENT)
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-scp-1.2.1/lib/net/scp/download.rb:156:in `new'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-scp-1.2.1/lib/net/scp/download.rb:156:in `read_file'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-scp-1.2.1/lib/net/scp/download.rb:51:in `read_directive_state'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 levels) in start_command'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:311:in `call'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:311:in `process'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `block in preprocess'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `each'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `preprocess'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:269:in `wait'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/net-scp-1.2.1/lib/net/scp.rb:321:in `download!'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/photocopier-0.0.10/lib/photocopier/ssh.rb:24:in `get'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:46:in `block (2 levels) in <class:SSH>'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:64:in `download_remote_db'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/deployer/ssh.rb:18:in `push_db'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:58:in `block in push'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:34:in `block in handle_options'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `each'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:32:in `handle_options'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/lib/wordmove/cli.rb:57:in `push'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/brettgolding/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /Users/brettgolding/.rbenv/versions/2.1.1/bin/wordmove:23:in `load'
	from /Users/brettgolding/.rbenv/versions/2.1.1/bin/wordmove:23:in `<main>'`

**Comment by pioneerskies** [comment]
Well...trying to keep on :)

1) never post output containing passwords! Please, edit your posts and delete the password
2) do not use sshpass if you're working w/ SSH, use pubkey authentication instead. sshpass is a bit un-secure and the workflow using pubkey auth is really straightforward
3)

    "/Dropbox/htdocs/thelanguagepeople/wp-content/languages/." failed: No such file or directory (2)
0 files to consider

hey...this path doesn't exists on your system, I bet! :P Try

    ls /Dropbox/htdocs/thelanguagepeople

in your terminal; I think you'll get back something similar to

    No such file or directory

**Comment by pioneerskies** [comment]
I'm closing due to inactivity. Feel free to reopen if you need
