### ISSUE TITLE
Push Issue

### ISSUE THREAD

**Issue by paperrobots** [welaika/wordmove#170]
Getting this error on push. I checked my Movefile and it validates. 

    /usr/lib/ruby/1.9.1/psych.rb:203:in `parse': (<unknown>): found character that cannot start any token while scanning for the next token at line 14 column 15 (Psych::SyntaxError)
	from /usr/lib/ruby/1.9.1/psych.rb:203:in `parse_stream'
	from /usr/lib/ruby/1.9.1/psych.rb:151:in `parse'
	from /usr/lib/ruby/1.9.1/psych.rb:127:in `load'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:58:in `fetch_movefile'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/deployer/base.rb:20:in `deployer_for'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/lib/wordmove/cli.rb:56:in `push'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/lib/ruby/gems/1.9.1/gems/wordmove-1.2.0/bin/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'

**Comment by paperrobots** [comment]
So my Movefile validated, but I decided to take what the Linter spit out and put it in my file and now that seemed to work. Why that is I don't know.

**Comment by pioneerskies** [comment]
What have you effectively done on line 14? Not clear to me w/o a code snippet from the `Movefile`

**Comment by pioneerskies** [comment]
Sorry I'm closing due to inactivity, but feel free to continue and reopen the discussion
