### ISSUE TITLE
FTP Timeout

### ISSUE THREAD

**Issue by ohryan** [welaika/wordmove#229]
I'm seeing the following error after the Pulling Database step:

```/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:152:in `rbuf_fill'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:1108:in `readline'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:289:in `getline'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:300:in `getmultiline'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:318:in `getresp'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:338:in `voidresp'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:249:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:247:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:160:in `initialize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:140:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:140:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/photocopier-1.0.0/lib/photocopier/ftp.rb:37:in `session'
	from /Library/Ruby/Gems/2.0.0/gems/photocopier-1.0.0/lib/photocopier/ftp.rb:17:in `put_file'
	from /Library/Ruby/Gems/2.0.0/gems/photocopier-1.0.0/lib/photocopier/adapter.rb:12:in `put'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:69:in `remote_put'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:98:in `download_remote_db'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:40:in `pull_db'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:49:in `block in pull'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in `block in handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `handle_options'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:48:in `pull'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/wordmove-1.3.1/exe/wordmove:6:in `<top (required)>'
	from /usr/bin/wordmove:23:in `load'
	from /usr/bin/wordmove:23:in `<main>'
```

If I'm not mistaken, this means that FTP is timing out. 

Would it be possible to add a config parameter for FTP timeout?

**Comment by Shotman** [comment]
I have the exact same problem and still have no idea how to fix it, I can sync everything but the database ...

**Comment by mukkoo** [comment]
Thanks @Shotman we will add it in documentation
