### ISSUE TITLE
Vagrant push mysqldump failing

### ISSUE THREAD

**Issue by der-lukas** [welaika/wordmove#237]
Hey! I've done exactly what's described in this Wiki (https://github.com/welaika/wordmove/wiki/Getting-Wordmove-installed-in-VVV-(or-any-Vagrant))!

But there are two ways that go wrong:

**1. case (SSH):**
- I start `vagrant ssh`.
- But in SSH I don't have lftp and I'm not able to install it, so going to "/srv/www/myproject" and `wordmove push --all` doesn't work because it says lftp isn't installed. But "mysqldump" works.

**2. case (local):**
- I just go to my project-folder (`cd vagrant-local/www/myproject`)
- I run `wordmove push --all`
- Now all the files get pushed, but the database can't be imported because it says "mysqldump: command not found"

**UPDATE**
I managed to install lftp in the box with `sudo apt-get install lftp`, but `wordmove push --db` still doesn't work... I get this message error-message `501 Syntax error in IP address`.

Here's the complete message:

    vagrant@vvv:~$ cd /srv/www/bit
    vagrant@vvv:/srv/www/bit$ wordmove push --db
    
    ▬▬ ✓ Pushing Database
    remote | write /DEV/bit/wp-content/dump.php
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:327:in `getresp': 501 Syntax error in IP address (Net::FTPPermError)
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:339:in `voidresp'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:362:in `block in voidcmd'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:360:in `voidcmd'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:376:in `sendport'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:387:in `makeport'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:422:in `transfercmd'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:547:in `block (2 levels) in storbinary'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:199:in `with_binary'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:546:in `block in storbinary'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:545:in `storbinary'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:694:in `putbinaryfile'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:722:in `put'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/photocopier-1.0.0/lib/photocopier/ftp.rb:17:in `put_file'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/photocopier-1.0.0/lib/photocopier/adapter.rb:12:in `put'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:69:in `remote_put'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:98:in `download_remote_db'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:18:in `push_db'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:60:in `block in push'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in `block in handle_options'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `each'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `handle_options'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:59:in `push'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/exe/wordmove:6:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/wordmove:23:in `load'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/wordmove:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

This is my Movefile:

    local:
      vhost: "http://bit.dev"
      # wordpress_path: "/Users/lukas/vagrant-local/www/bit/htdocs" # when I'm not using SSH
      wordpress_path: "/srv/www/bit/htdocs"  

      database:
        name: "bit"
        user: "wp"
        password: "wp"
        host: "127.0.0.1"

    staging:
      vhost: "http://xxx/DEV/bit"
      wordpress_path: "/DEV/bit"

    database:
        name: "xxx"
        user: "xxx"
        password: "xxx"
        host: "xxx"
        # port: "3308" # Use just in case you have exotic server config

      ftp: 
        host: "xxxx"
        password: "xxx"
        user: "xxx"

Thanks in advance,
Lukas

**Comment by der-lukas** [comment]
Okay, I could fix it by just turning on "passive mode" for the FTP connection...
