### ISSUE TITLE
Could not parse PKey: no start line (ArgumentError)

### ISSUE THREAD

**Issue by neocamel** [welaika/wordmove#240]
I'm trying to get wordmove working in Windows 7, using Git Bash for my command line tool.  When I run 'wordmove push -e staging -d'  I get the following output (database password OMITTED):

C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/key_factory.rb:77:in `read': Could not parse PKey: no start line (ArgumentError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/key_factory.rb:77:in `load_data_private_key'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/key_factory.rb:42:in `load_private_key'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/authentication/key_manager.rb:142:in `sign'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/authentication/key_manager.rb:119:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/authentication/key_manager.rb:119:in `each_identity'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/authentication/session.rb:79:in `block in authenticate'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/authentication/session.rb:66:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh/authentication/session.rb:66:in `authenticate'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.3.beta1/lib/net/ssh.rb:211:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/photocopier-1.0.0/lib/photocopier/ssh.rb:70:in `session'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/photocopier-1.0.0/lib/photocopier/ssh.rb:43:in `exec!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ssh.rb:50:in `remote_run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ssh.rb:58:in `download_remote_db'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ssh.rb:15:in `push_db'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:60:in `block in push'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in `block in handle_options'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `handle_options'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:59:in `push'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/wordmove-1.3.1/exe/wordmove:6:in `<top (required)>'
        from C:/Ruby22-x64/bin/wordmove:23:in `load'
        from C:/Ruby22-x64/bin/wordmove:23:in `<main>'

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
mysqldump --host=localhost --user=neocamel_skeleto --password=OMITTED neocamel_skeleto --result-file=/home/neocamel/public_html/skeleton/wp-content/dump.sql
   remote | mysqldump --host=localhost --user=neocamel_skeleto --password=OMITTED neocamel_skeleto --result-file=/home/neocamel/public_html/skeleton/wp-content/dump.sql

Any ideas?

**Comment by mukkoo** [comment]
We have just published a disclaimer about Windows Support https://github.com/welaika/wordmove/wiki/Windows-(un)support-disclaimer
GLHF
