### ISSUE TITLE
wordmove push --all not working on Windows

### ISSUE THREAD

**Issue by steoo** [welaika/wordmove#252]
I'm getting this error while trying to execute: 
```
remote | put: D:/Development/webstorm10workspace/wordpress/wp-content/dump.sql /var/www/wordpress/wp-content/dump.sql
mysql --host=127.0.0.1 --user=root --password=mypsw --database=wordpress --execute=SOURCE\ /var/www/wordpress/wp-content/dump.sql
   remote | mysql --host=127.0.0.1 --user=root --password=mypsw --database=wordpress --execute=SOURCE\ /var/www/wordpress/wp-content/dump.sql
   remote | delete: /var/www/wordpress/wp-content/dump.sql
    local | rm D:/Development/webstorm10workspace/wordpress/wp-content/dump.sql
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/base.rb:136:in 'run': Return code reports an error (Wordmove::ShellCommandError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ssh.rb:20:in 'push_db'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:60:in 'block in push'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in 'block in handle_options'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in 'each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in 'handle_options'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:59:in 'push'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in 'run'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in 'dispatch'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in 'start'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/wordmove-1.3.1/exe/wordmove:6:in '<top (required)>'
        from C:/Ruby200-x64/bin/wordmove:23:in 'load'
        from C:/Ruby200-x64/bin/wordmove:23:in '<main>'
```

**Comment by steoo** [comment]
The issue was that windows does not have a `rm` command. I installed GnuWin32 and it works now, but it does not install anything on the remote server now.

**Comment by mukkoo** [comment]
We have just published a disclaimer about Windows Support https://github.com/welaika/wordmove/wiki/Windows-(un)support-disclaimer
GLHF

**Comment by TheAggressive** [comment]
With the windows update that is coming this summer that will have Ubuntu command line in the windows environment, will this help with these issues?

**Comment by TheAggressive** [comment]
I **can confirm** that wordmove does in fact work perfectly using bash on Ubuntu on Windows, which is in beta right now.

**Comment by pioneerskies** [comment]
1) I'm going to close this issue 'cause it's old.
2) the new cool thing bash on Ubuntu on Windows is exciting and if someone using windows would like to write an how to wiki page it would be even moar exciting.
3) in Wordmove 1.3.1there was a blocking bug. We have yanked the version away from rubygems.org, so issues about that version are no more considered as valid. Please update and open a new issue if necessary.

Cheers
