### ISSUE TITLE
Pulling database

### ISSUE THREAD

**Issue by asikora** [welaika/wordmove#257]
Hi,

I have a problem with pulling db form production server. I'am using ssh and I get following error:

```
mysqldump --host=127.0.0.1 --user=user --password=password dbname --result-file=file
/usr/local/rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.2/lib/net/ssh/authentication/agent/socket.rb:92:in `identities': could not get identity count (Net::SSH::Authentication::AgentError)
        from /usr/local/rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.2/lib/net/ssh/authentication/key_manager.rb:104:in `each_identity'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.2/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.2/lib/net/ssh/authentication/session.rb:79:in `block in authenticate'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.2/lib/net/ssh/authentication/session.rb:66:in `each'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.2/lib/net/ssh/authentication/session.rb:66:in `authenticate'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.2/lib/net/ssh.rb:211:in `start'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/photocopier-1.0.0/lib/photocopier/ssh.rb:70:in `session'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/photocopier-1.0.0/lib/photocopier/ssh.rb:43:in `exec!'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/wordmove-1.3.1/lib/wordmove/deployer/ssh.rb:50:in `remote_run'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/wordmove-1.3.1/lib/wordmove/deployer/ssh.rb:58:in `download_remote_db'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/wordmove-1.3.1/lib/wordmove/deployer/ssh.rb:30:in `pull_db'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/wordmove-1.3.1/lib/wordmove/cli.rb:49:in `block in pull'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in `block in handle_options'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `each'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `handle_options'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/wordmove-1.3.1/lib/wordmove/cli.rb:48:in `pull'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/wordmove-1.3.1/exe/wordmove:6:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.5/bin/wordmove:23:in `load'
        from /usr/local/rvm/gems/ruby-2.1.5/bin/wordmove:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

Files are copying over ssh without any problem. User and password is correct.

**Comment by pioneerskies** [comment]
What's your OS?
`wordmove pull -l`, for example, really success to connect to the remote server?
Are you using an identity manager or something exotic to manage you're ssh connections?

**Comment by asikora** [comment]
Sorry for the late response. I was using mobaxterm for ssh connection and somehow it didn't set all the enviroment varibles correctly.
