### ISSUE TITLE
Pushing Database runs error free, yet database was not updated on remote (running on VVV ssh)

### ISSUE THREAD

**Issue by leifjohn** [welaika/wordmove#282]
I have tried running wordmove push and I keep getting this error

`/var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/wordpress_directory.rb:26:in 'join': no implicit conversion of nil into String (TypeError)`

**Comment by leifjohn** [comment]
This is the full output I am getting when, for example, just trying to push the database:

```
$ wordmove push -e staging -d

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/wordpress_directory.rb:26:in 'join': no implicit conversion of nil into String (TypeError)
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/wordpress_directory.rb:26:in 'path'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:15:in 'push_db'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:60:in 'block in push'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in 'block in handle_options'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in 'each'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in 'handle_options'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:59:in 'push'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in 'run'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in 'dispatch'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in 'start'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/exe/wordmove:6:in '<top (required)>'
	from /usr/local/bin/wordmove:23:in 'load'
	from /usr/local/bin/wordmove:23:in '<main>'
```

**Comment by leifjohn** [comment]
Okay so I figured out you have to have a value set for the wordpress_path for the remote server in the move file. I had left it blank since the wordpress_path was the root path for the FTP user. I added a forward slash '/' so that I would not get the nil error. But now I am getting a new error. Here is the latest terminal output:

```
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | write /wp-content/dump.php
    local | download http://staging.examplesite.org/wp-content/dump.php?shared_key=987s6df9g876sd9f8g67s9d6f7gs8dfg67s8d6fg7df67gsd7f6g > /home/username/vagrant-local/www/examplesite/htdocs/wp-content/remote-backup-1456327916.sql
   remote | delete: /wp-content/dump.php
mysqldump --host=localhost --user=wpawef --password=wph34aasd examplesite --result-file=/home/username/vagrant-local/www/examplesite/htdocs/wp-content/dump.sql
    local | mysqldump --host=localhost --user=wpawef --password=wph34aasd examplesite --result-file=/home/username/vagrant-local/www/examplesite/htdocs/wp-content/dump.sql
/var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/deployer/base.rb:136:in `run': Return code reports an error (Wordmove::ShellCommandError)
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/deployer/base.rb:208:in `save_local_db'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:19:in `push_db'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:60:in `block in push'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in `block in handle_options'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `each'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `handle_options'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/lib/wordmove/cli.rb:59:in `push'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/2.1.0/gems/wordmove-1.3.1/exe/wordmove:6:in `<top (required)>'
	from /usr/local/bin/wordmove:23:in `load'
	from /usr/local/bin/wordmove:23:in `<main>'
```

**Comment by leifjohn** [comment]
I've made some further progress. Since I am using VVV, I came across the wiki for getting wordmove instlalled on VVV:

https://github.com/welaika/wordmove/wiki/Getting-Wordmove-installed-in-VVV-(or-any-Vagrant)

It appears to be working BUT nothing has changed on my remote site. The database was not updated yet I did not receive any errors when I ran `wordmove push -e staging -d`

It did the mysqldymp, get, delete on the remote, mysqldump, adapt dump on the local, put, mysql, delete on remote

I checked the wp-content folder on the remove and there is a dump.mysql file there. I'm not sure what else to do now?

**Comment by leifjohn** [comment]
I tried running 

`wordmove push -e staging --all`

I received an error and figured I needed to install sshpass:

`sudo apt-get install sshpass`

I received a different error and decided I needed to use ftp instead of ssh so I changed `ssh` in the movefile to `ftp` and installed lftp:

`sudo apt-get install lftp`

Then again I ran:

`wordmove push -e staging --all`

Interestingly enough, it migrated all of the files accordingly without error, yet when it came to pushing the database I got this error:

```
▬▬ ✓ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | write /wp-content/dump.php
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:327:in `getresp': 500 Illegal PORT command (Net::FTPPermError)
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:339:in `voidresp'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:362:in `block in voidcmd'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:360:in `voidcmd'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:376:in `sendport'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:387:in `makeport'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:422:in `transfercmd'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:547:in `block (2 levels) in storbinary'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:199:in `with_binary'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:546:in `block in storbinary'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:545:in `storbinary'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:694:in `putbinaryfile'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:722:in `put'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/photocopier-1.0.0/lib/photocopier/ftp.rb:17:in `put_file'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/photocopier-1.0.0/lib/photocopier/adapter.rb:12:in `put'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:69:in `remote_put'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:98:in `download_remote_db'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/deployer/ftp.rb:18:in `push_db'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:60:in `block in push'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:36:in `block in handle_options'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `each'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:34:in `handle_options'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/lib/wordmove/cli.rb:59:in `push'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/wordmove-1.3.1/exe/wordmove:6:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/wordmove:23:in `load'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/wordmove:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

So I went back into my movefile and changed the `ftp` back to `ssh` and just ran:

`wordmove push -e staging -d`

which ran error-free but did not actually update the database on the remote server. So I am still stumped :(

**Comment by mattydaw** [comment]
Sounds almost identical to my issue too :-(  #286 
Particularly have the ssh database push runs error free but doesn't result in the db being updated.

**Comment by leifjohn** [comment]
After changing to a different remote server where I had better SSH permissions, I was able to get things working.

**Comment by pioneerskies** [comment]
Can we close this issue so far?

**Comment by leifjohn** [comment]
yes thank you.
