### ISSUE TITLE
Undefined method `local_mu_plugins_dir' when pulling mu-plugins

### ISSUE THREAD

**Issue by duncansf** [welaika/wordmove#294]
Hi,

The following error occurs and prevents pull '--all' from completing from production to local. Note that I don't have a mu-plugins directory on the production server.

OS: Ubuntu 14.04 LTS using VVV
Ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
Wordmove 1.4.0-pre10

```
vagrant@vvv:/srv/www/mywebsite/htdocs$ wordmove pull -e production -m

== Using Movefile: ./Movefile ========================================

== Pulling Mu Plugins ================================================
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/wordmove-1.4.0.pre10/lib/wordmove/deployer/base.rb:90:in `block (2 levels) in <class:Base>': undefined method `local_mu_plugins_dir' for #<Wordmove::Deployer::SSH:0x00000001e23280> (NoMethodError)
        from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/wordmove-1.4.0.pre10/lib/wordmove/cli.rb:69:in `block in pull'
        from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/wordmove-1.4.0.pre10/lib/wordmove/cli.rb:37:in `block in handle_options'
        from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/wordmove-1.4.0.pre10/lib/wordmove/cli.rb:36:in `each'
        from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/wordmove-1.4.0.pre10/lib/wordmove/cli.rb:36:in `handle_options'
        from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/wordmove-1.4.0.pre10/lib/wordmove/cli.rb:68:in `pull'
        from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/wordmove-1.4.0.pre10/exe/wordmove:6:in `<top (required)>'
        from /home/vagrant/.rvm/gems/ruby-2.2.1/bin/wordmove:23:in `load'
        from /home/vagrant/.rvm/gems/ruby-2.2.1/bin/wordmove:23:in `<main>'
        from /home/vagrant/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/vagrant/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```
		
Best regards,
Duncan

**Comment by taliesinpenbardd** [comment]
Agreed. Have to do a wordmove pull -utpldv to make it work.

OS: Ubuntu trusty64 using VVV
Ruby 2.2.1p85
Wordmove 1.4.0.pre10

```
▬▬ ✓ Pulling Mu Plugins ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/wordmove-1.4.0.pre10/lib/wordmove/deployer/base.rb:90:in `block (2 levels) in <class:Base>': undefined method `local_mu_plugins_dir' for #<Wordmove::Deployer::SSH:0x00000002668c60> (NoMethodError)
	from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/wordmove-1.4.0.pre10/lib/wordmove/cli.rb:69:in `block in pull'
	from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/wordmove-1.4.0.pre10/lib/wordmove/cli.rb:37:in `block in handle_options'
	from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/wordmove-1.4.0.pre10/lib/wordmove/cli.rb:36:in `each'
	from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/wordmove-1.4.0.pre10/lib/wordmove/cli.rb:36:in `handle_options'
	from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/wordmove-1.4.0.pre10/lib/wordmove/cli.rb:68:in `pull'
	from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/vagrant/.rvm/gems/ruby-2.2.1/gems/wordmove-1.4.0.pre10/exe/wordmove:6:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-2.2.1/bin/wordmove:23:in `load'
	from /home/vagrant/.rvm/gems/ruby-2.2.1/bin/wordmove:23:in `<main>'
	from /home/vagrant/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/vagrant/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```
Want any other intel to help debug ?
Thanks by advance.
Luc

**Comment by mukkoo** [comment]
@taliesinpenbardd can you retry with wordmove 2.0, seems that this problem is already fixes.

**Comment by duncansf** [comment]
Yup, it seems to work :) Thanks for your great work and dedication!

**Comment by mukkoo** [comment]
YEAH! Thank you to have tried it.
