### ISSUE TITLE
Undefined method `to_sym' 

### ISSUE THREAD

**Issue by AndreaBarghigiani** [welaika/wordmove#305]
Hi team,
I am trying to use wordmove inside a VVV machine. I've followed [these steps](https://github.com/welaika/wordmove/wiki/Getting-Wordmove-installed-in-VVV-%28or-any-Vagrant%29) (btw thanks for the guide) but when I try to run a simple `wordmove pull -t` I get the following error:

```
/usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/base.rb:21:in `deployer_for': undefined method `to_sym' for nil:NilClass (NoMethodError)
Did you mean?  to_s
        from /usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:63:in `pull'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/wordmove:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/wordmove:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

I've tried to search for previou issues but with no luck, can you be so kind to let me understand what's happening?

Thank you for your great work,
Andrea

**Comment by pioneerskies** [comment]
Hey Andrea,

that seems to be related to the `Movefile` configuration. Could you safely paste it?
