### ISSUE TITLE
Error retrieving dump.sql.gz

### ISSUE THREAD

**Issue by paulmist** [welaika/wordmove#360]
Hello.

I'm getting the following output during a database pull:

```
▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=localhost --user=•••• --password=•••• --result-file="/Users/paulmist/Workspace/WATB/WATB/Site_2016/Build/src/wp-content/local-backup-1484574489.sql" watb
Warning: Using a password on the command line interface can be insecure.
gzip --best --force "/Users/paulmist/Workspace/WATB/WATB/Site_2016/Build/src/wp-content/local-backup-1484574489.sql"
    local | gzip --best --force "/Users/paulmist/Workspace/WATB/WATB/Site_2016/Build/src/wp-content/local-backup-1484574489.sql"
   remote | mysqldump --host=•••••••••••••••• --user=••••• --password=•••••••••••• --result-file="/home/w/a/•••/public_html/wp-content/dump.sql" watb
gzip --best --force "/home/w/a/••••/public_html/wp-content/dump.sql"
   remote | gzip --best --force "/home/w/a/•••/public_html/wp-content/dump.sql"
   remote | get: /home/w/a/••••/public_html/wp-content/dump.sql.gz /Users/paulmist/Workspace/WATB/WATB/Site_2016/Build/src/wp-content/dump.sql.gz
/Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/net-scp-1.2.1/lib/net/scp.rb:365:in `block (3 levels) in start_command': SCP did not finish successfully (127):  (Net::SCP::Error)
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/net-ssh-3.2.0/lib/net/ssh/connection/channel.rb:607:in `do_close'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:614:in `channel_close'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:479:in `dispatch_incoming_packets'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:225:in `preprocess'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:206:in `process'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `block in loop'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `loop'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/net-ssh-3.2.0/lib/net/ssh/connection/session.rb:170:in `loop'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/net-ssh-3.2.0/lib/net/ssh/connection/channel.rb:269:in `wait'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/net-scp-1.2.1/lib/net/scp.rb:321:in `download!'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/photocopier-1.1.1/lib/photocopier/ssh.rb:17:in `get'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:49:in `block (2 levels) in <class:SSH>'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:71:in `download_remote_db'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:37:in `pull_db'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:69:in `block in pull'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:37:in `block in handle_options'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `each'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `handle_options'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:68:in `pull'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0@global/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0/bin/wordmove:23:in `load'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0/bin/wordmove:23:in `<main>'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/paulmist/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```
Any help would be appreciated.

Thanks.

**Comment by pioneerskies** [comment]
Hi,

can you check if the file at `/Users/paulmist/Workspace/WATB/WATB/Site_2016/Build/src/wp-content/dump.sql.gz` is actually crated?

Are you sure the folder `/home/w/a/•••/public_html/wp-content` exists remotely?

Adding [these](https://github.com/welaika/wordmove/wiki/Contributor-Guide#bug-reporting) info to the ticked could also be useful in some cases.

**Comment by paulmist** [comment]
Hi, 

I can confirm that all folders exist.

The ``dump.sql.gz`` is being created remotely but it seems there a problem then retrieving it.

Here's some more details:
OS: macOS 10.12
Ruby Version: 2.3.3 + RVM

**Comment by paulmist** [comment]
Any answers to this problem?

**Comment by pioneerskies** [comment]
We have continued working with DBs push/pull over ssh with success. The only thing I could say is that we have just updated `net-ssh` library which Wordmove relies on. You should give it another chance.

**Comment by electricarts** [comment]
Hi, i'm getting the same error when trying to pull a database. The file "dump.sql.gz" exist in the specified remote folder! 

macOS 10.12.6
WordMove 2.0.2
Ruby 2.4.0

```
▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=localhost --user=**** --password=**** --result-file="/Users/mario/Sites/***********.dev/wp-content/local-backup-1505317218.sql" **********
Warning: Using a password on the command line interface can be insecure.
gzip --best --force "/Users/mario/Sites/**********.dev/wp-content/local-backup-1505317218.sql"
    local | gzip --best --force "/Users/mario/Sites/**********.dev/wp-content/local-backup-1505317218.sql"
   remote | mysqldump --host=******** --user=******** --password=************** --result-file="/home/strato/www/re/www.*********.de/htdocs/***********.de/wp-content/dump.sql" DB*******
www.********.de@ssh.strato.de's password:
gzip --best --force "/home/strato/www/re/www.********.de/htdocs/**********.de/wp-content/dump.sql"
   remote | gzip --best --force "/home/strato/www/re/www.*********.de/htdocs/***********.de/wp-content/dump.sql"
   remote | get: /home/strato/www/re/www.***********.de/htdocs/************.de/wp-content/dump.sql.gz /Users/mario/Sites/*************.dev/wp-content/dump.sql.gz
/Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-scp-1.2.1/lib/net/scp.rb:365:in `block (3 levels) in start_command': SCP did not finish successfully (1): scp: /home/strato/www/re/www.resonanzpunkt.de/htdocs/Resonanzpunkt.de/wp-content/dump.sql.gz: No such file or directory (Net::SCP::Error)
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh/connection/channel.rb:607:in `do_close'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:564:in `channel_closed'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:675:in `channel_close'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:540:in `dispatch_incoming_packets'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:237:in `ev_preprocess'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:99:in `each'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:99:in `ev_preprocess'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:216:in `process'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh/connection/channel.rb:269:in `wait'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-scp-1.2.1/lib/net/scp.rb:321:in `download!'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/photocopier-1.1.3/lib/photocopier/ssh.rb:17:in `get'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/wordmove-2.0.2/lib/wordmove/deployer/ssh.rb:49:in `block (2 levels) in <class:SSH>'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/wordmove-2.0.2/lib/wordmove/deployer/ssh.rb:71:in `download_remote_db'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/wordmove-2.0.2/lib/wordmove/deployer/ssh.rb:37:in `pull_db'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/wordmove-2.0.2/lib/wordmove/cli.rb:69:in `block in pull'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/wordmove-2.0.2/lib/wordmove/cli.rb:37:in `block in handle_options'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/wordmove-2.0.2/lib/wordmove/cli.rb:36:in `each'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/wordmove-2.0.2/lib/wordmove/cli.rb:36:in `handle_options'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/wordmove-2.0.2/lib/wordmove/cli.rb:68:in `pull'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/wordmove-2.0.2/exe/wordmove:6:in `<top (required)>'
	from /Users/mario/.rvm/rubies/ruby-2.4.0/bin/wordmove:23:in `load'
	from /Users/mario/.rvm/rubies/ruby-2.4.0/bin/wordmove:23:in `<main>'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/mario/.rvm/gems/ruby-2.4.0@global/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by pioneerskies** [comment]
@electricarts Wordmove 2.0.2 is anyway an old version. Wold you like to retry with the latest one?

Cheers

**Comment by electricarts** [comment]
Ok. Updated to 2.1.3. When trying to pull the db i'm getting this error now: 

```
✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/Users/mario/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.3/lib/wordmove/deployer/base.rb:24:in `deployer_for': undefi
ned method `[]' for nil:NilClass (NoMethodError)
        from /Users/mario/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.3/lib/wordmove/cli.rb:63:in `pull'
        from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_com
mand'
        from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /Users/mario/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.3/exe/wordmove:6:in `<top (required)>'
        from /Users/mario/.rvm/gems/ruby-2.4.0/bin/wordmove:23:in `load'
        from /Users/mario/.rvm/gems/ruby-2.4.0/bin/wordmove:23:in `<main>'
        from /Users/mario/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/mario/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by pioneerskies** [comment]
@electricarts I bet you received a message lile

```
Starting from 2.1.0 you'll need to add the global section in your Movefile:
        global:
            sql_adapter: "default"
    Or you can spawn a new one with `wordmove init` (backup the old one!)
```

during the upgrade. In the README there's also the complete example.

**Comment by electricarts** [comment]
Hi Allessandro,

thanks for your help! I started with a new Movefile. ;-)

But now this happens: 

```

✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=localhost --user=root --password=root --result-file="/Users/mario/Sites/resonanzpun
kt.dev/wp-content/local-backup-1505376302.sql" resonanzpunkt
Warning: Using a password on the command line interface can be insecure.
gzip --best --force "/Users/mario/Sites/********.dev/wp-content/local-backup-1505376302.sql"
    local | gzip --best --force "/Users/mario/Sites/***********.dev/wp-content/local-backup-1505376302.sql"
   remote | mysqldump --host=****** --user=******* --password=********** --result-file="/hom
e/strato/www/re/www.********.de/htdocs/*********.de/wp-content/dump.sql" DB2784053
/Users/mario/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/socket.rb:227:in `getaddrinfo': getaddrinfo: nodename nor ser
vname provided, or not known (SocketError)
        from /Users/mario/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/socket.rb:227:in `foreach'

        from /Users/mario/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/socket.rb:617:in `tcp'
        from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh/transport/session.rb:70:in
`initialize'
        from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh.rb:233:in `new'
        from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-ssh-4.1.0/lib/net/ssh.rb:233:in `start'
        from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/photocopier-1.1.3/lib/photocopier/ssh.rb:70:in `sessi
on'
        from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/photocopier-1.1.3/lib/photocopier/ssh.rb:43:in `exec!
'
        from /Users/mario/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.3/lib/wordmove/deployer/ssh.rb:50:in `remote_ru
n'
        from /Users/mario/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.3/lib/wordmove/deployer/ssh.rb:63:in `download_
remote_db'
        from /Users/mario/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.3/lib/wordmove/deployer/ssh/default_sql_adapter
.rb:28:in `adapt_remote_db!'
        from /Users/mario/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.3/lib/wordmove/deployer/ssh.rb:35:in `pull_db'
        from /Users/mario/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.3/lib/wordmove/cli.rb:69:in `block in pull'
        from /Users/mario/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.3/lib/wordmove/cli.rb:37:in `block in handle_op
tions'
        from /Users/mario/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.3/lib/wordmove/cli.rb:36:in `each'
        from /Users/mario/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.3/lib/wordmove/cli.rb:36:in `handle_options'
        from /Users/mario/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.3/lib/wordmove/cli.rb:68:in `pull'
        from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_com
mand'
        from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /Users/mario/.rvm/gems/ruby-2.4.0@global/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /Users/mario/.rvm/gems/ruby-2.4.0/gems/wordmove-2.1.3/exe/wordmove:6:in `<top (required)>'
        from /Users/mario/.rvm/gems/ruby-2.4.0/bin/wordmove:23:in `load'
        from /Users/mario/.rvm/gems/ruby-2.4.0/bin/wordmove:23:in `<main>'
        from /Users/mario/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/mario/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

```

Cheers
Mario

**Comment by electricarts** [comment]
Seems to be a DNS problem. Restarted macOS and this error is gone. But now i've the exact same error from the beginning:

```
/Users/mario/.rvm/gems/ruby-2.4.0@global/gems/net-scp-1.2.1/lib/net/scp.rb:365:in `block (3 levels) in start_com
mand': SCP did not finish successfully (1): scp: /home/strato/www/re/www.*******.de/htdocs/******.d
e/wp-content/dump.sql.gz: No such file or directory (Net::SCP::Error)

```
The directory (wp-content) and the actual file (dump.sql.gz) are there. 

Wordmove 2.1.3
Ruby 2.4
macOS 10.12.6

**Comment by pioneerskies** [comment]
I have really no idea what's up there... is a *plain* `scp` working? E.g.

```bash
scp user@host:/home/strato/www/re/www.*******.de/htdocs/******.d
e/wp-content/dump.sql.gz ~/Desktop/dump.sql.gz
```

**Comment by electricarts** [comment]
Hi Allessandro,

i'm sure i has something to do with the hosting package. The clients site is hosted at "Strato", the worst hosting company here in Germany. I think, it's a problem with the path to the WP Installation. 

This is what they say: 

> The absolute path to your web hosting package:
> /home/strato/www/first two letters/www.desiredname.de/htdocs/

> Please replace desiredname.de with any domain in your web hosting package, and replace the part named /de/ with the first two letters of the domain you selected. Important: If you forward a domain from your package to a sub-directory through domain forwarding, the directory name must also be entered when specifying the path so that the scripts work.

For my installation this would be:
```
/home/strato/www/re/www.re**********.de/htdocs/**********.de
```
But when when i upload a php script to show me the path of the installation, the path is different: 

```
/home/strato/http/premium/rid/01/64/54120164/htdocs
```
An scp with

```
scp www.********.de@ssh.strato.de:/home/strato/www/re/www.re***********.de/htdocs/***********.de/wp-content/dump.sql.gz ~/Desktop/dump.sql.gz

```
gives me a "No such file or directory". 

What downloads the db is a

```
scp www.********.de@ssh.strato.de:/***********.de/wp-content/dump.sql.gz ~/Desktop/dump.sql.gz
```

But with this path the wordmove pull --db gives me a 

```
Can't create/write to file '/***********.de/wp-content/dump.sql' (Errcode: 2) (Wordmove::ShellCommandError)

```

So i would need to use different paths. I really don't know whats going on here but it's not the first time i've trouble with this hosting company. Nice info from them is also, that when using ssh with public key i've to use a password too. So when using 
```
wordmove pull --all 
```
i've to type the password several times.

**Comment by pioneerskies** [comment]
Dear @electricarts ,

your's a quite strange - and I think irritant front your point of view - scenario.

All that I can do - and this is a really poor support for which I'm really sorry... :( - is to point out spotted ideas.

No more. But not less :)

So: what does this command

```scp www.********.de@ssh.strato.de:/home/strato/http/premium/rid/01/64/54120164/htdocs/wp-content/dump.sql.gz ~/Desktop/dump.sql.gz```

returns to you?

**Comment by electricarts** [comment]
The result for this is: 

> scp: /home/strato/http/premium/rid/01/64/54120164/htdocs/wp-content/dump.sql.gz: No such file or directory

**Comment by pioneerskies** [comment]
Sorry but this is too old and specific; I've to close w/o solution :(
