### ISSUE TITLE
Can't push the database

### ISSUE THREAD

**Issue by radovanovigor** [welaika/wordmove#371]
Hi,
When I run the `wordmove push --all` command, the command stuck at:

```
/var/lib/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:57:in `remote_run': Error code 1 returned by command "mysqldump --host=localhost --user=xxx --password=xxx --result-file="/home/xxx/new/wp-content/dump.sql" xxx": mysqldump: Can't create/write to file '/home/xxx/new/wp-content/dump.sql' (Errcode: 2 "No such file or directory") (Wordmove::ShellCommandError)
        from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:67:in `download_remote_db'
        from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:18:in `push_db'
        from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:86:in `block in push'
        from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:37:in `block in handle_options'
        from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `each'
        from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `handle_options'
        from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:85:in `push'
        from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /var/lib/gems/2.3.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>'
        from /usr/local/bin/wordmove:22:in `load'
        from /usr/local/bin/wordmove:22:in `<main>'
```

**Comment by wdss93** [comment]
+1

**Comment by radovanovigor** [comment]
I've fixed this error by uploading the website for the first time to the remote host. That's probably a glitch on the hosting side. After you upload the website, `wordmove push --all` will work.
