### ISSUE TITLE
Could not parse PKey: no start line (OpenSSL::PKey::PKeyError)

### ISSUE THREAD

**Issue by ashmatadeen** [welaika/wordmove#388]
I can successfully `wordmove pull -u` but pulling the database with `wordmove pull -d` results in `Could not parse PKey: no start line (OpenSSL::PKey::PKeyError)`. I am using Wordmove 2.0.0 and the OpelSSL version is 1.0.1f 6 Jan 2014. It's a connection over SSH with a passphrase protected key.

Does anyone have any insights?

```bash
vagrant@vvv:/srv/www/project--123$ wordmove pull -d

▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ ✓ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=127.0.0.1 --user=wp --password=wp --result-file="/vagrant/www/project-123/public/wp-content/local-backup-1492529682.sql" acn
gzip --best --force "/vagrant/www/project-123/public/wp-content/local-backup-1492529682.sql"
    local | gzip --best --force "/vagrant/www/project-123/public/wp-content/local-backup-1492529682.sql"
   remote | mysqldump --host=localhost --user=xxx --password=xxx --result-file="/server/www/123/staging/public/wp-content/dump.sql" acn_staging
/usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/cipher_factory.rb:97: warning: constant OpenSSL::Cipher::Cipher is deprecated
/usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/cipher_factory.rb:72: warning: constant OpenSSL::Cipher::Cipher is deprecated
/usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/key_factory.rb:77:in `read': Could not parse PKey: no start line (OpenSSL::PKey::PKeyError)
	from /usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/key_factory.rb:77:in `load_data_private_key'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/key_factory.rb:42:in `load_private_key'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/key_manager.rb:224:in `block in load_identities'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/key_manager.rb:217:in `map'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/key_manager.rb:217:in `load_identities'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/key_manager.rb:101:in `each_identity'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:79:in `block in authenticate'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:66:in `each'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.2.0/lib/net/ssh.rb:236:in `start'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/photocopier-1.1.1/lib/photocopier/ssh.rb:70:in `session'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/photocopier-1.1.1/lib/photocopier/ssh.rb:43:in `exec!'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:56:in `remote_run'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:67:in `download_remote_db'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/wordmove-2.0.0/lib/wordmove/deployer/ssh.rb:37:in `pull_db'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:69:in `block in pull'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:37:in `block in handle_options'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `each'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:36:in `handle_options'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/wordmove-2.0.0/lib/wordmove/cli.rb:68:in `pull'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/wordmove-2.0.0/exe/wordmove:6:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.4.0/bin/wordmove:22:in `load'
	from /usr/local/rvm/gems/ruby-2.4.0/bin/wordmove:22:in `<main>'
	from /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by pioneerskies** [comment]
We have just updated with official support to ruby 2.4 and updated dependencies, `net-ssh` included. Could you please update and retry?

**Comment by ashmatadeen** [comment]
That worked like a charm. Thanks @pioneerskies
