### ISSUE TITLE
Something went wrong with Movefile

### ISSUE THREAD

**Issue by mukkoo** [welaika/wordmove#434]
All `wordmove doctor` checks passed but with `wordmove pull` I have this error:
```
▬▬ ✓ Using Movefile: ./Movefile ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
/Users/mukkoo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/wordmove-2.3.0/lib/wordmove/deployer/base.rb:24:in `deployer_for': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/mukkoo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/wordmove-2.3.0/lib/wordmove/cli.rb:68:in `pull'
	from /Users/mukkoo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/mukkoo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/mukkoo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/mukkoo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/mukkoo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/wordmove-2.3.0/exe/wordmove:6:in `<top (required)>'
	from /Users/mukkoo/.rbenv/versions/2.4.1/bin/wordmove:22:in `load'
	from /Users/mukkoo/.rbenv/versions/2.4.1/bin/wordmove:22:in `<main>'
```

**Comment by pioneerskies** [comment]
<img width="856" alt="image preview" src="https://user-images.githubusercontent.com/904690/34255368-ac0ceeba-e650-11e7-808c-19d0aa2f22e9.png">

It was a misunderstanding: errors should me more evident anyway
