### ISSUE TITLE
WP-CLI is not installed or not in your $PATH

### ISSUE THREAD

**Issue by byron222** [welaika/wordmove#471]
when i try

`wordmove pull -d`

i get this error

```
local | adapt dump for vhost
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/wordmove-3.0.2/lib/wordmove/sql_adapter/wpcli.rb:14:in `command': WP-CLI is not installed or not in your $PATH (Wordmove::UnmetPeerDependencyError)
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/wordmove-3.0.2/lib/wordmove/deployer/ssh/wpcli_sql_adapter.rb:49:in `wpcli_search_replace'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/wordmove-3.0.2/lib/wordmove/deployer/ssh/wpcli_sql_adapter.rb:37:in `adapt_remote_db!'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/wordmove-3.0.2/lib/wordmove/deployer/ssh.rb:46:in `pull_db'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/wordmove-3.0.2/lib/wordmove/cli.rb:79:in `block in pull'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/wordmove-3.0.2/lib/wordmove/cli.rb:42:in `block in handle_options'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/wordmove-3.0.2/lib/wordmove/cli.rb:41:in `each'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/wordmove-3.0.2/lib/wordmove/cli.rb:41:in `handle_options'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/wordmove-3.0.2/lib/wordmove/cli.rb:78:in `pull'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/wordmove-3.0.2/exe/wordmove:6:in `<top (required)>'
        from /root/.rbenv/versions/2.4.2/bin/wordmove:23:in `load'
        from /root/.rbenv/versions/2.4.2/bin/wordmove:23:in `<main>
```

**Comment by pioneerskies** [comment]
Oh my!

At least tell me that `which wp` in your terminal is not working! 😵 😀 

If WP-CLI is installed and you your $PATH, then it should *really*® work: we simply do a system call from inside wordmove. Is it possible that you have it installed but available under a different executable name than `wp`?

**Comment by pioneerskies** [comment]
Any update?

**Comment by pioneerskies** [comment]
Last bump!? 😉
