### ISSUE TITLE
I can't push/pull wp-theme, plugins, uploads by FTP

### ISSUE THREAD

**Issue by SID-Viibar** [welaika/wordmove#477]
I can't push wp-theme locally to remote. I run wordmove in FTP mode.

command
```bash
$ wordmove pull -e staging --plugins
```
Error messages
```
    ℹ️  info | Using .env file: ./.env

▬▬ Using Movefile: ./movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Pulling Plugins ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | get_directory: / /local_wp_directory .git/ .gitignore node_modules/ bin/ tmp/* Gemfile* movefile.yml wp/wp-config.php wp/wp-content/*.sql.gz *.orig vendor/ /* /wp-content/* /wp-content/ /wp-content/plugins/
/Users/operator/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/photocopier-1.2.0/lib/photocopier/ftp.rb:23:in `get_directory': wrong number of arguments (given 4, expected 2..3) (ArgumentError)
	from /Users/operator/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/wordmove-3.1.0/lib/wordmove/deployer/ftp.rb:64:in `block (2 levels) in <class:FTP>'
	from /Users/operator/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/wordmove-3.1.0/lib/wordmove/deployer/base.rb:70:in `block (2 levels) in <class:Base>'
	from /Users/operator/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/wordmove-3.1.0/lib/wordmove/cli.rb:79:in `block in pull'
	from /Users/operator/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/wordmove-3.1.0/lib/wordmove/cli.rb:42:in `block in handle_options'
	from /Users/operator/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/wordmove-3.1.0/lib/wordmove/cli.rb:41:in `each'
	from /Users/operator/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/wordmove-3.1.0/lib/wordmove/cli.rb:41:in `handle_options'
	from /Users/operator/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/wordmove-3.1.0/lib/wordmove/cli.rb:78:in `pull'
	from /Users/operator/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/operator/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/operator/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/operator/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/operator/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/wordmove-3.1.0/exe/wordmove:6:in `<top (required)>'
	from /Users/operator/.rbenv/versions/2.4.0/bin/wordmove:22:in `load'
	from /Users/operator/.rbenv/versions/2.4.0/bin/wordmove:22:in `<main>'
```

I researched the code, It means that remote_put_directory(https://github.com/welaika/wordmove/blob/master/lib/wordmove/deployer/base.rb#L98) is given 4 parameters. And it calls method of photocopier(https://github.com/welaika/photocopier/blob/master/lib/photocopier/ftp.rb#L28). 

I don't know Why the number of arguments are changed, Any ideas to fix it or avoid?

I'm sorry my poor English 😂

**Comment by pioneerskies** [comment]
@SID-Viibar this should be fixed with https://github.com/welaika/wordmove/releases/tag/v3.1.1

Would be awesome to have your feedback.

**Comment by SID-Viibar** [comment]
It works! Thank you so much！
