### ISSUE TITLE
FTPS: -a and -d blocked, other is working

### ISSUE THREAD

**Issue by davidegiunchidiennea** [welaika/wordmove#490]
Following the issue #489 , some comands like these:
```
wordmove pull/push -u
wordmove pull/push -t
wordmove pull/push -p
```
are working perfectly. But if i run some others commands, i get some kind of errors.
```

▬▬[0;97;49m Using Movefile: ./Movefile.yml [0m▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬[0;97;49m Pulling Database [0m▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
[0;36;49m    local[0m[0;30;49m | [0mmysqldump --host=mysql --user=root --result-file="/var/www/html/wpstaging2/wp-content/local-backup-1533224157.sql" wpstaging2
/opt/rh/rh-ruby24/root/usr/share/ruby/net/protocol.rb:176:in `rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from /opt/rh/rh-ruby24/root/usr/share/ruby/net/protocol.rb:154:in `readuntil'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/net/ftp.rb:1447:in `gets'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/net/ftp.rb:1452:in `readline'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/net/ftp.rb:435:in `getline'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/net/ftp.rb:447:in `getmultiline'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/net/ftp.rb:464:in `getresp'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/net/ftp.rb:484:in `voidresp'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/net/ftp.rb:377:in `block in connect'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/monitor.rb:214:in `mon_synchronize'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/net/ftp.rb:373:in `connect'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/net/ftp.rb:266:in `initialize'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/net/ftp.rb:170:in `new'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/net/ftp.rb:170:in `open'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/photocopier-1.3.0/lib/photocopier/ftp/session.rb:15:in `initialize'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/photocopier-1.3.0/lib/photocopier/ftp.rb:45:in `new'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/photocopier-1.3.0/lib/photocopier/ftp.rb:45:in `session'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/photocopier-1.3.0/lib/photocopier/ftp.rb:16:in `put_file'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/photocopier-1.3.0/lib/photocopier/adapter.rb:12:in `put'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/wordmove-3.2.0/lib/wordmove/deployer/ftp.rb:90:in `remote_put'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/wordmove-3.2.0/lib/wordmove/deployer/ftp.rb:118:in `download_remote_db'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/wordmove-3.2.0/lib/wordmove/deployer/ftp.rb:44:in `pull_db'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/wordmove-3.2.0/lib/wordmove/cli.rb:79:in `block in pull'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/wordmove-3.2.0/lib/wordmove/cli.rb:42:in `block in handle_options'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/wordmove-3.2.0/lib/wordmove/cli.rb:41:in `each'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/wordmove-3.2.0/lib/wordmove/cli.rb:41:in `handle_options'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/wordmove-3.2.0/lib/wordmove/cli.rb:78:in `pull'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /opt/rh/rh-ruby24/root/usr/local/share/gems/gems/wordmove-3.2.0/exe/wordmove:6:in `<top (required)>'
	from /opt/rh/rh-ruby24/root/usr/local/bin/wordmove:23:in `load'
	from /opt/rh/rh-ruby24/root/usr/local/bin/wordmove:23:in `<main>'
[0;33;49m   remote[0m[0;30;49m | [0mwrite /wordpress/staging/wp-staging2/wp-content/dump.php
```
the local dump is created correctly, but after that the program wait 1 minute and it give this error (seems related to the dump.php creation).  
I get error on another command:
```
wordmove pull -w

▬▬[0;97;49m Using Movefile: ./Movefile.yml [0m▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬[0;97;49m Pulling wordpress core [0m▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
[0;33;49m   remote[0m[0;30;49m | [0mget_directory: /wordpress/staging/wp-staging2 /var/www/html/wpstaging2 .git/ .gitignore node_modules/ bin/ tmp/* Gemfile* Movefile movefile movefile.yml movefile.yaml wp-config.php wp-content/*.sql.gz wp-content/*.sql *.orig wp-content/*
[0;33;49m    ℹ️  info[0m[0;30;49m | [0mlftp -c 'set ftp:list-options -a; set cmd:fail-exit true; open -p 990 ftps://davide.giunchi:XXXXX@ftp-share.mysite.it; find -d 1 /wordpress/staging/wp-staging2 || mkdir -p /wordpress/staging/wp-staging2; lcd /var/www/html/wpstaging2; cd /wordpress/staging/wp-staging2; mirror --delete --use-cache --verbose --no-perms --allow-suid --no-umask --parallel=5 --exclude-glob .git/ --exclude-glob .gitignore --exclude-glob node_modules/ --exclude-glob bin/ --exclude-glob tmp/* --exclude-glob Gemfile* --exclude-glob Movefile --exclude-glob movefile --exclude-glob movefile.yml --exclude-glob movefile.yaml --exclude-glob wp-config.php --exclude-glob wp-content/*.sql.gz --exclude-glob wp-content/*.sql --exclude-glob *.orig --exclude-glob wp-content/*'
/wordpress/staging/wp-staging2/
Getting files information (4%) [Delaying before reconnect: 29]
```
and it get stuck on the "Getting files information (4%)", like the previous ticket.

I'm using wordmove 3.2.0 on a centos7 with ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux].
The movefile.yml is the attached one.

Thank you
[movefile.txt](https://github.com/welaika/wordmove/files/2254148/movefile.txt)

**Comment by pioneerskies** [comment]
@davidegiunchidiennea for sure we had a problem honouring `passive` option in commands which implied transfer of a single file (`-d` is one of them). So my guess is that those connections was ignoring `passive: true` thus failing.

Try to update to version `3.2.1` and tell me. Sincerely, looking at the code, I have a couple doubts about the correctness fo FTPS handling - when issuing single file transfer commands...but let's try step by step.

> As a not-so-side note: tomorrow I'll go on vacation until 27 August ^^

**Comment by davidegiunchidiennea** [comment]
I've upgraded now to 3.2.1, but i still have the same errors with pull -d and -w

**Comment by pioneerskies** [comment]
@davidegiunchidiennea pls try 3.2.2 - it is anyway a correct improvement.

If it won't work I'll elaborate a bit in order to have a clearer scenario, but I'm not sure how to and if iterate again.

Thanks

**Comment by davidegiunchidiennea** [comment]
@pioneerskies sorry, i thought that 3.2.1 was the latest version. Now i've upgraded to 3.2.2, but i still get the same errors  
thank you

**Comment by davidegiunchidiennea** [comment]
Hi @pioneerskies , 
I hope that your vacation went fine :)
I've bypassed this problem by using the ftp server via SFTP and not FTPS (since it seems to me that SFTP has a better support on wordmove), now it's working good.
I leave this issue open as the bug is still present, but you can close it if you prefer

Thank you,
Regards

**Comment by pioneerskies** [comment]
Hi @davidegiunchidiennea ,

they were the finest thing of the entire year! Thank you! 🎉 

SFTP is an SSH subsystem, so it's completely supported, simpler, safer, faster, foo-er, bar-er. But I'd like to investigate more on the issue. Do you have a way to provide a test FTPS server? I don't have one and it's too rough to publish a new release for every try/fail session ^^;
