### ISSUE TITLE
Cannot push to WP Engine

### ISSUE THREAD

**Issue by frontenddevguy** [welaika/wordmove#519]
I tried setting up Wordmove to push to a staging server on WP Engine.

They have GIT integration but it rejects images!

I either get:
ssh: connect to host xx.xx.xx.xx port 22: Operation timed out
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/io.c(453) [sender=2.6.9]

or:
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/io.c(453) [sender=2.6.9]

trying different port settings, based on advice given by WPE.

Maybe an error in config, but I went through all the options with their support guy.

Is there some reason why this may not work with WP Engine?

**Comment by mechdog** [comment]
I did a little digging and it actually does not appear to be the gzip command causing the issue. If I take line 79 of ssh.rb and duplicate it, I get the same error. I tried a few other things where I would put say just tell @copier.exec! to run some random command first. When I do that it crashes with he same error on a command that just ran. 

```
def download_remote_db(local_gizipped_dump_path)
        remote_dump_path = remote_wp_content_dir.path("dump.sql")
        # dump remote db into file
        remote_run mysql_dump_command(remote_options[:database], remote_dump_path)
        remote_run mysql_dump_command(remote_options[:database], remote_dump_path)
        remote_run compress_command(remote_dump_path)
        remote_dump_path += '.gz'
        # download remote dump
        remote_get(remote_dump_path, local_gizipped_dump_path)
        remote_delete(remote_dump_path)
      end
```
So for this, the first one runs and the second then errors out
```
wordmove pull -d

▬▬ Using Movefile: ./movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=127.0.0.1 --port=8889 --user=[blank] --password=[blank] --result-file="/sites/cooper2019/wp-content/local-backup-1559324264.sql" cooper2019
mysqldump: [Warning] Using a password on the command line interface can be insecure.
    local | gzip -9 -f "/sites/cooper2019/wp-content/local-backup-1559324264.sql"
   remote | mysqldump --host=127.0.0.1 --user=[blank] --password=[blank] --result-file="/home/wpe-user/sites/cooper2019/wp-content/dump.sql" wp_cooper2019
   remote | mysqldump --host=127.0.0.1 --user=[blank] --password=[blank] --result-file="/home/wpe-user/sites/cooper2019/wp-content/dump.sql" wp_cooper2019
/Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:70:in `remote_run': Error code 1 returned by command "mysqldump --host=127.0.0.1 --user=cooper2019 --password=gfLKCQyxY1TANr3aFwpZ --result-file="/home/wpe-user/sites/cooper2019/wp-content/dump.sql" wp_cooper2019":  (Wordmove::ShellCommandError)
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:80:in `download_remote_db'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh/wpcli_sql_adapter.rb:34:in `adapt_remote_db!'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:48:in `pull_db'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:79:in `block in pull'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:42:in `block in handle_options'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:41:in `each'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:41:in `handle_options'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:78:in `pull'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/exe/wordmove:6:in `<top (required)>'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/bin/wordmove:23:in `load'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/bin/wordmove:23:in `<main>'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `eval'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `<main>'

```

So it looks to have more to do with running more then one command over an existing. If I run it once so that the 'dump.sql' is created and sitting there, then comment out the line that runs that dump and jsut leave 'remote_run compress_command(remote_dump_path)' it will compress the file with no error and then error out on the remote_get command down below:

```
wordmove pull -d

▬▬ Using Movefile: ./movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Pulling Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
    local | mysqldump --host=127.0.0.1 --port=8889 --user=[blank] --password=[blank] --result-file="/sites/cooper2019/wp-content/local-backup-1559324538.sql" cooper2019
mysqldump: [Warning] Using a password on the command line interface can be insecure.
    local | gzip -9 -f "/sites/cooper2019/wp-content/local-backup-1559324538.sql"
   remote | gzip -9 -f "/home/wpe-user/sites/cooper2019/wp-content/dump.sql"
   remote | get: /home/wpe-user/sites/cooper2019/wp-content/dump.sql.gz /sites/cooper2019/wp-content/dump.sql.gz
/Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-scp-1.2.1/lib/net/scp.rb:365:in `block (3 levels) in start_command': SCP did not finish successfully (1):  (Net::SCP::Error)
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-ssh-4.2.0/lib/net/ssh/connection/channel.rb:607:in `do_close'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:573:in `channel_closed'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:684:in `channel_close'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:549:in `dispatch_incoming_packets'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:246:in `ev_preprocess'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:99:in `each'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:99:in `ev_preprocess'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-ssh-4.2.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:225:in `process'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `loop'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-ssh-4.2.0/lib/net/ssh/connection/session.rb:178:in `loop'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-ssh-4.2.0/lib/net/ssh/connection/channel.rb:269:in `wait'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/net-scp-1.2.1/lib/net/scp.rb:321:in `download!'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/photocopier-1.3.2/lib/photocopier/ssh.rb:16:in `get'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:58:in `block (2 levels) in <class:SSH>'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:84:in `download_remote_db'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh/wpcli_sql_adapter.rb:34:in `adapt_remote_db!'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:48:in `pull_db'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:79:in `block in pull'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:42:in `block in handle_options'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:41:in `each'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:41:in `handle_options'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/lib/wordmove/cli.rb:78:in `pull'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/gems/wordmove-4.0.1/exe/wordmove:6:in `<top (required)>'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/bin/wordmove:23:in `load'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/bin/wordmove:23:in `<main>'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `eval'
	from /Users/markkenney/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `<main>'
```

If I follow the same pattern and remove the 'remote_run compress_command(remote_dump_path)' it will now run the remote_get command and actually get the file.

Not sure if this helps at all?

**Comment by mechdog** [comment]
Apologize for the dirty code in advance:

I made a local version of the ssh_options to try something:
```
def initialize(environment, options)
        super
        ssh_options = remote_options[:ssh]
        @ssh_options = ssh_options
        if simulate? && ssh_options[:rsync_options]
          ssh_options[:rsync_options].concat(" --dry-run")
        elsif simulate?
          ssh_options[:rsync_options] = "--dry-run"
        end

        @copier = Photocopier::SSH.new(ssh_options).tap { |c| c.logger = logger }

        @local_dump_path = local_wp_content_dir.path("dump.sql")
        @local_backup_path = local_wp_content_dir.path("local-backup-#{Time.now.to_i}.sql")
        @local_gzipped_dump_path = local_dump_path + '.gz'
        @local_gzipped_backup_path = local_wp_content_dir
                                     .path("#{environment}-backup-#{Time.now.to_i}.sql.gz")
      end
```

Then I updated the 'download_remote_db' to create a new @copier each time around.
```
def download_remote_db(local_gizipped_dump_path)
        remote_dump_path = remote_wp_content_dir.path("dump.sql")
        # dump remote db into file
        remote_run mysql_dump_command(remote_options[:database], remote_dump_path)
        @copier = Photocopier::SSH.new(@ssh_options).tap { |c| c.logger = logger }
        remote_run compress_command(remote_dump_path)
        remote_dump_path += '.gz'
        # download remote dump
        @copier = Photocopier::SSH.new(@ssh_options).tap { |c| c.logger = logger }
        remote_get(remote_dump_path, local_gizipped_dump_path)
        remote_delete(remote_dump_path)
      end
```

That will successfully run. Not sure what that means. But thought I would mention it to see if it means something.

**Comment by pioneerskies** [comment]
Hey there, I'm going to close this in the hope to squash it in #528.

Tell me if I'm wrong
