### ISSUE TITLE
Problem installing WordMove

### ISSUE THREAD

**Issue by Flushdrew** [welaika/wordmove#536]
hello,
i have the following error when installing wordmove and can't resolve it: 

```
MBP-de-Julien:~ julienguiard$ wordmove -v
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate photocopier-1.1.1, because activesupport-5.2.3 conflicts with activesupport (~> 4.2.0) (Gem::ConflictError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1411:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/wordmove-2.0.0/lib/wordmove.rb:14:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/wordmove-2.0.0/exe/wordmove:5:in `<top (required)>'
	from /usr/local/bin/wordmove:22:in `load'
	from /usr/local/bin/wordmove:22:in `<main>'
```

Do you have an idea? Thank you

**Comment by pioneerskies** [comment]
Hi @Flushdrew ,

we require at least ruby 2.4.0. Update your ruby version - I'd advice to go for the latest stable anyway - and re-install wordmove. This will fix your problem for sure®

I'll close this one, but feel free to reopen and/or to give us some news

:)
