### ISSUE TITLE
Always errors pushing a database (Net::SSH::ConnectionTimeout)

### ISSUE THREAD

**Issue by thetwopct** [welaika/wordmove#542]
I use WordMove a lot, it saves me a ton of time, thanks so much for creating it.

I have a problem with pushing a database to staging or production, everything else works fine (themes, uploads, etc), but even though I've used wordMove maybe 100x times, pushing the database **NEVER** works. I'd love to get to the bottom of it before I move to Capistrano or something else. 

My hosting company reports that it appears the script is brute forcing the server (some of their comments below). As I say it only happens when I am pushing the database, all other transfers are fine. 

Can anyone help me?

Here's the error message I get:

```
▬▬ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | mysqldump --host=localhost --port=9000 --user=dbuser --password=password --result-file="/home/www/wp-content/dump.sql" dbname
   remote | gzip -9 -f "/home/www/wp-content/dump.sql"
   remote | get: /home/www/wp-content/dump.sql.gz /Users/james/Sites/wp-content/production-backup-1567963477.sql.gz
   remote | delete: /home/www/wp-content/dump.sql.gz
    local | mysqldump --host=localhost --user=root --password=root --result-file="/Users/james/Sites/wp-content/dump.sql" dbname
mysqldump: [Warning] Using a password on the command line interface can be insecure.
    local | adapt dump for vhost
    local | wp search-replace http://currentsite.com https://newsite.com --quiet --skip-columns=guid --all-tables --allow-root
    local | adapt dump for wordpress_path
    local | wp search-replace /Users/james/Sites/thesite /home/www --quiet --skip-columns=guid --all-tables --allow-root
    local | mysqldump --host=localhost --user=root --password=root --result-file="/Users/james/Sites/wp-content/search_replace_dump.sql" dbname
mysqldump: [Warning] Using a password on the command line interface can be insecure.
    local | gzip -9 -f "/Users/james/Sites/wp-content/search_replace_dump.sql"
   remote | put: /Users/james/Sites/wp-content/search_replace_dump.sql.gz /home/www/wp-content/dump.sql.gz
Traceback (most recent call last):
	28: from /Users/james/.rbenv/versions/2.6.3/bin/wordmove:23:in `<main>'
	27: from /Users/james/.rbenv/versions/2.6.3/bin/wordmove:23:in `load'
	26: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/exe/wordmove:6:in `<top (required)>'
	25: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	24: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	23: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	22: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	21: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/cli.rb:102:in `push'
	20: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/cli.rb:41:in `handle_options'
	19: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/cli.rb:41:in `each'
	18: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/cli.rb:42:in `block in handle_options'
	17: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/cli.rb:103:in `block in push'
	16: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/deployer/ssh.rb:38:in `push_db'
	15: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/deployer/ssh/wpcli_sql_adapter.rb:19:in `adapt_local_db!'
	14: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/deployer/ssh.rb:91:in `import_remote_dump'
	13: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/deployer/ssh.rb:58:in `block (2 levels) in <class:SSH>'
	12: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/photocopier-1.3.3.pre3/lib/photocopier/adapter.rb:7:in `put'
	11: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/photocopier-1.3.3.pre3/lib/photocopier/ssh.rb:20:in `put_file'
	10: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/photocopier-1.3.3.pre3/lib/photocopier/ssh.rb:72:in `session'
	 9: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `start'
	 8: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `new'
	 7: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:70:in `initialize'
	 6: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/2.6.0/socket.rb:631:in `tcp'
	 5: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/2.6.0/socket.rb:227:in `foreach'
	 4: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/2.6.0/socket.rb:227:in `each'
	 3: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/2.6.0/socket.rb:641:in `block in tcp'
	 2: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/2.6.0/socket.rb:137:in `connect'
	 1: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/2.6.0/socket.rb:64:in `connect_internal'
/Users/james/.rbenv/versions/2.6.3/lib/ruby/2.6.0/socket.rb:64:in `connect': Operation timed out - connect(2) for 123.456.789.123:22 (Errno::ETIMEDOUT)
	22: from /Users/james/.rbenv/versions/2.6.3/bin/wordmove:23:in `<main>'
	21: from /Users/james/.rbenv/versions/2.6.3/bin/wordmove:23:in `load'
	20: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/exe/wordmove:6:in `<top (required)>'
	19: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	18: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	17: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	16: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	15: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/cli.rb:102:in `push'
	14: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/cli.rb:41:in `handle_options'
	13: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/cli.rb:41:in `each'
	12: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/cli.rb:42:in `block in handle_options'
	11: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/cli.rb:103:in `block in push'
	10: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/deployer/ssh.rb:38:in `push_db'
	 9: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/deployer/ssh/wpcli_sql_adapter.rb:19:in `adapt_local_db!'
	 8: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/deployer/ssh.rb:91:in `import_remote_dump'
	 7: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wordmove-4.0.2.pre4/lib/wordmove/deployer/ssh.rb:58:in `block (2 levels) in <class:SSH>'
	 6: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/photocopier-1.3.3.pre3/lib/photocopier/adapter.rb:7:in `put'
	 5: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/photocopier-1.3.3.pre3/lib/photocopier/ssh.rb:20:in `put_file'
	 4: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/photocopier-1.3.3.pre3/lib/photocopier/ssh.rb:72:in `session'
	 3: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `start'
	 2: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `new'
	 1: from /Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:56:in `initialize'
/Users/james/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:90:in `rescue in initialize': Net::SSH::ConnectionTimeout (Net::SSH::ConnectionTimeout)
```
_______________________________________________________________________

**My movefile.yml important bits:**

 ```
database:
    name: dbname
    user: root
    password: "root"
    host: localhost

production:
  vhost: http://domain.com
  wordpress_path: /home/www 

  database:
    name: dbname
    user: dbuser
    password: password
    host: localhost
    port: 9000

  ssh:
    host: 123.456.789.123
    user: sshusername
    port: 22
    rsync_options: '-v'
```

**My MySQL tunnel setup before running wordmove push:**

`ssh -L 9000:localhost:3306 sshusername@123.456.789.123`

**Version**

`wordmove -v = 4.0.2.pre4`
WordMove doctor is all green ticks

**SSH config file:**

```
Host *
  ServerAliveInterval 300
  ServerAliveCountMax 2
```

**Manual?**

Using WP-CLI, I export the database, move it to the file via RSYNC, import it, then search-replace. So manually, the process works.

**Hosting and Feedback**

I have experienced this failing with both WP Engine, and Litespeed-based servers via Guru.co.uk

I asked my hosting company why it fails, here are some entries from conversations back and forth with them:

> Yesterday it appeared you were activating brute force protection systems on the server, hence my suggestion to ensure the script is configured correctly and with sane connection limits and retry attempts duration etc.

> The commands happening automatically may be due to the configuration of your script, we wouldnt be able to advise or offer advice regarding the script you are using, the cause certainly wouldnt be server side and we recommend you tweak and tune your script accordingly or contact the developer of said script for assistance.

> The brute force block isn't triggered by the commands you are running. It's based on how many connections you are opening in a set interval. 

> I can see in excess of 13 connections to the server in the space of 20 seconds. 

> As for the multiple connections issues, I'm not entirely sure why your client is making so many of them and it could be worth using another client if you continue to experience those issues.

So, any ideas what could be happening? Can I limit the connections the script makes? Can I limit the amount of SSH connections perhaps?

Many thanks in advance

**Comment by pioneerskies** [comment]
Hi. 4.0.2pre4 was released in order to counter this thing with WPE policies...so...sad to hear that from you.

You could try to add this to you ssh_config

```
Host *
  ControlMaster auto
  ControlPath /tmp/master-%r@%h:%p
  Compression yes
```

Also just for the specific host you're testing.

I have to ask you to follow up on https://github.com/welaika/wordmove/issues/528 which is the issue where most of the discussion happened, since I'm not able to manage a big spread of information ;)

Thanks in advance

**Comment by thetwopct** [comment]
Just FYI this is happening with non-WPE hosts, so focus should not be on WPE only. Never the less I will try the above and keep monitoring the situation in #528

**Comment by pioneerskies** [comment]
I see. Let's try that option above and to understand if even with other hosting provider the problem source could be assimilable.

Thank you
