### ISSUE TITLE
DB update failed with "Error code 1 returned by command "mysqldump ..."

### ISSUE THREAD

**Issue by ahmedmusawir** [welaika/wordmove#558]
Here is the error: 
```
Ahmeds-Capitan-2:NEW-INNKEEPER shourav$ wordmove push -d

▬▬ Using Movefile: ./movefile.yml ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

▬▬ Pushing Database ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
   remote | mysqldump --host=localhost --user=devhtmlf_wpadmin --password=Keya5392 --result-file="/home2/devhtmlf/public_html/innkeeper-new-stg/wp-content/dump.sql" --max_allowed_packet=1G devhtmlf_innkeeper_new_db
Traceback (most recent call last):
	15: from /usr/local/bin/wordmove:23:in `<main>'
	14: from /usr/local/bin/wordmove:23:in `load'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/wordmove-4.0.1/exe/wordmove:6:in `<top (required)>'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	 9: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	 8: from /usr/local/lib/ruby/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/cli.rb:102:in `push'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/cli.rb:41:in `handle_options'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/cli.rb:41:in `each'
	 5: from /usr/local/lib/ruby/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/cli.rb:42:in `block in handle_options'
	 4: from /usr/local/lib/ruby/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/cli.rb:103:in `block in push'
	 3: from /usr/local/lib/ruby/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:37:in `push_db'
	 2: from /usr/local/lib/ruby/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh/wpcli_sql_adapter.rb:6:in `backup_remote_db!'
	 1: from /usr/local/lib/ruby/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:79:in `download_remote_db'
/usr/local/lib/ruby/gems/2.6.0/gems/wordmove-4.0.1/lib/wordmove/deployer/ssh.rb:70:in `remote_run': Error code 1 returned by command "mysqldump --host=localhost --user=devhtmlf_wpadmin --password=Keya5392 --result-file="/home2/devhtmlf/public_html/innkeeper-new-stg/wp-content/dump.sql" --max_allowed_packet=1G devhtmlf_innkeeper_new_db": error: Found option without preceding group in config file: /home2/devhtmlf/.my.cnf at line: 1 (Wordmove::ShellCommandError)
Fatal error in defaults handling. Program aborted

```
Plz let me know what I'm doing wrong ...
```
MacOS 10.12.6
wordmove -v 4.0.1
```

**Comment by pioneerskies** [comment]
Hello :)

It seems you've done nothing wrong, but on you remote server you have a misconfiguration. When running `mysqldump [...]` it returned the error

> Found option without preceding group in config file: /home2/devhtmlf/.my.cnf at line: 1

Wordmove is not involved here: it's just reporting the error happened with `mysqldump`. I think you'd better to search for that error :)

Cheers and good luck 🤞
