### ISSUE TITLE
Open or closing parentheses in password causes wordmove to fail.

### ISSUE THREAD

**Issue by kauaicreative** [welaika/wordmove#569]
Open or closing parentheses in password causes all wordmove commands to fail. e.g. `password: "xx(xx"`

windows 10 Linux subsystem
wordmove 5.0.0 (previous version of wordmove did not have this issue)
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-gnu]

```
/var/lib/gems/2.6.0/gems/wordmove-5.0.0/lib/wordmove/logger.rb:10: warning: regular expression has ']' without escape
Traceback (most recent call last):
        18: from /usr/local/bin/wordmove:23:in `<main>'
        17: from /usr/local/bin/wordmove:23:in `load'
        16: from /var/lib/gems/2.6.0/gems/wordmove-5.0.0/exe/wordmove:6:in `<top (required)>'
        15: from /var/lib/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        14: from /var/lib/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        13: from /var/lib/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        12: from /var/lib/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        11: from /var/lib/gems/2.6.0/gems/wordmove-5.0.0/lib/wordmove/cli.rb:91:in `pull'
        10: from /var/lib/gems/2.6.0/gems/wordmove-5.0.0/lib/wordmove/cli.rb:39:in `handle_options'
         9: from /var/lib/gems/2.6.0/gems/wordmove-5.0.0/lib/wordmove/cli.rb:39:in `each'
         8: from /var/lib/gems/2.6.0/gems/wordmove-5.0.0/lib/wordmove/cli.rb:40:in `block in handle_options'
         7: from /var/lib/gems/2.6.0/gems/wordmove-5.0.0/lib/wordmove/cli.rb:92:in `block in pull'
         6: from /var/lib/gems/2.6.0/gems/wordmove-5.0.0/lib/wordmove/deployer/ssh.rb:108:in `block (2 levels) in <class:SSH>'
         5: from /var/lib/gems/2.6.0/gems/wordmove-5.0.0/lib/wordmove/logger.rb:21:in `task'
         4: from /usr/lib/ruby/2.6.0/logger.rb:472:in `add'
         3: from /usr/lib/ruby/2.6.0/logger.rb:582:in `format_message'
         2: from /var/lib/gems/2.6.0/gems/wordmove-5.0.0/lib/wordmove/logger.rb:10:in `block in initialize'
         1: from /var/lib/gems/2.6.0/gems/wordmove-5.0.0/lib/wordmove/logger.rb:10:in `new'
/var/lib/gems/2.6.0/gems/wordmove-5.0.0/lib/wordmove/logger.rb:10:in `initialize': end pattern with unmatched parenthesis: /127.0.0.1|\/\/x.test|\/mnt\/c\/www\/choo
sehope\/|5j(3XS]ap2|localhost|\/\/www.x.com|gro|\/home\/kauaigro\/sites\/x\// (RegexpError)
```

**Comment by pioneerskies** [comment]
@kauaicreative this was auto-closed by the commit, but please give me some feedback after updating to 5.0.1 ;)

Thanks to have pointed out the problem.

**Comment by kauaicreative** [comment]
Thanks for the quick fix! 
Works perfectly!
