### ISSUE TITLE
'Stack level too deep' error on Windows

### ISSUE THREAD

**Issue by frontenddevguy** [welaika/wordmove#655]
**Describe the bug**

On Windows 10 Pro with a newly installed Ruby environment and latest Wordmove, I get the following error, with:
wordmove pull -e production --themes:

```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:13:in `fetch': stack level too deep (SystemStackError)
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:25:in `fetch'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:25:in `fetch'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:25:in `fetch'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:25:in `fetch'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:25:in `fetch'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:25:in `fetch'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:25:in `fetch'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/wordmove-5.2.2/lib/wordmove/movefile.rb:25:in `fetch'
         ... 8723 levels...
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/wordmove-5.2.2/exe/wordmove:6:in `<top (required)>'
        from D:/Ruby31-x64/bin/wordmove:32:in `load'
        from D:/Ruby31-x64/bin/wordmove:32:in `<main>'

```
Running wordmove doctor works, but also returns the same error.

The wordmove command does not complete.

**Comment by alessandro-fazzi** [comment]
Hey @frontenddevguy ,

the stable release does not support ruby 3.1. The alpha release (`gem install wordmore --pre`) should work, but it never seen the stable channel's light so you should deeply test it on a staging environment before use it for production pushes.
