### ISSUE TITLE
Net:SSH AuthenticationFailed on remote mysqldump after rsync finished successfully

### ISSUE THREAD

**Issue by kLOsk** [welaika/wordmove#671]
**Describe the bug**

I'm also seeing the issue described [here](https://github.com/welaika/wordmove/issues/659) now. 
Local Mac environment is running MAMP 6.8 MySQL 5.7.39
Remote environment is Running Ubuntu 22.0.4.1 LTS MySQL 8
Open SSL installed via homebrew openssl@3/3.1.3
Remote uses  3.0.2-0ubuntu1.10 amd64

Is there any way that we can try using net-ssh.rb ver 7.1/7.2 @alessandro-fazzi @delphaber ? I tried to update the gems but have no clue about Ruby and couldn't not locate the gemfile that defines the net-ssh version being required by wordmove. Would be much appreciated, to either solve this, or find a workaround.

**Exception/trace**

<code><pre> remote | mysqldump --host=[secret] --user=[secret] --password=[secret] --result-file="[secret]/wp-content/dump.sql" dbname
Traceback (most recent call last):
	20: from /Users/klos/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in  '<main>'
	19: from /Users/klos/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	18: from /Users/klos/.rvm/gems/ruby-2.6.3/bin/wordmove:23:in `<main>'
	17: from /Users/klos/.rvm/gems/ruby-2.6.3/bin/wordmove:23:in `load'
	16: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/wordmove-5.2.2/exe/wordmove:6:in `<top (required)>'
	15: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	14: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	13: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	12: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	11: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/wordmove-5.2.2/lib/wordmove/cli.rb:115:in `push'
	10: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/wordmove-5.2.2/lib/wordmove/cli.rb:39:in `handle_options'
	 9: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/wordmove-5.2.2/lib/wordmove/cli.rb:39:in `each'
	 8: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/wordmove-5.2.2/lib/wordmove/cli.rb:40:in `block in handle_options'
	 7: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/wordmove-5.2.2/lib/wordmove/cli.rb:116:in `block in push'
	 6: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/wordmove-5.2.2/lib/wordmove/deployer/ssh.rb:37:in `push_db'
	 5: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/wordmove-5.2.2/lib/wordmove/deployer/ssh/wpcli_sql_adapter.rb:6:in `backup_remote_db!'
	 4: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/wordmove-5.2.2/lib/wordmove/deployer/ssh.rb:79:in `download_remote_db'
	 3: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/wordmove-5.2.2/lib/wordmove/deployer/ssh.rb:66:in `remote_run'
	 2: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/photocopier-1.4.1/lib/photocopier/ssh.rb:44:in `exec!'
	 1: from /Users/klos/.rvm/gems/ruby-2.6.3/gems/photocopier-1.4.1/lib/photocopier/ssh.rb:71:in `session'
/Users/klos/.rvm/gems/ruby-2.6.3/gems/net-ssh-6.1.0/lib/net/ssh.rb:268:in `start': Authentication failed for user user@ip (Net::SSH::AuthenticationFailed) </pre></code>

**Environment (please complete the following information):**

- OS: Mac OS Ventura 13.6
- Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
- Wordmove: 5.2.2

**Doctor**

* [x] running the `wordmove doctor` command returns all green

**Comment by bernhardmostrey** [comment]
Any updates on this? Having the same issue. Only on DigitalOcean servers.

**Comment by smilingpeanut** [comment]
Runing into the same problem with Sonona 14.3.1, Ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23], and Wordmove 5.2.2.

**Comment by bernhardmostrey** [comment]
Finally got it working by enabling password auth in the ssh settings of the server. I was using DigitalOcean, so you need to change the settings in two places.

**Comment by kLOsk** [comment]
Guys, I built a script that uses the movefile to push and pull databases to/from environments. So Its plug and play, simply use the new command when you want to push / pull a db from a wordpress site that was previously using wordmove

[https://github.com/kLOsk/WP-DBSync](https://github.com/kLOsk/WP-DBSync)
